# Generated by Django 3.0.2 on 2020-01-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='items',
            new_name='item',
        ),
    ]
